---
ENV: dev
aws_profile: default
job_name: test_cluster
user: alvin
key_pair: alvin

release_label: emr-5.21.0
emr_log_bucket: workbenches-emr-logs
subnetid: subnet-08af9b271c2d14237
emr_managed_slave_security_group: sg-01b09b9827de3b1cc
emr_managed_master_security_group: sg-0842fae4e52e5246c
emr_additional_slave_security_group: [sg-07a00b0167ffdc55b]
emr_additional_master_security_group: [sg-07a00b0167ffdc55b]


# 0 instance count will run single master node
instance_type: m4.4xlarge
instance_count: 3
instance_volume_size: 100
instance_profile: workbenches-emr-ec2-profile-role

cores_per_executor: 3
auto_terminate: False

spot_bid_price: 0.4

request_master_on_demand: True
request_core_on_demand: True

configuration: configurations.json
bootstrapaction: bootstrap-actions.json
steps: steps.json

pem_file_path: /Users/alvin/.ssh/id_rsa
script_to_run: test.sh

tags:
  - Key: "User"
    Value: "alvin"

  - Key: "Description"
    Value: "Data Science EMR Cluster"
